= Présentation Open Tracing

Mise Mise en scène 1 : giphy n'affiche plus les gifs
Architecture schéma schéma
Scénario Scénario 1: aucun outil
Scénario 2 : elk sans id corrélation corrélation
Scénario 3 : id de corrélation
Schéma étapes id corrélation corrélation
Solution technique manuelle
Solution Sleut Sleut spring boot
Ou brave braves brave
Résultats logs access, appli applications appli, élastique elk elk
Content Content


2ème problématique problématiques problématique : giphy gif giphy est lent
Vidéo Vidéos Vidéo atteinte 5 secondes
Sleut Sleut et brave brave se connectent à zipkin zipkin
Vidéo Vie.ecoles Vidéo zipkin zipkin
Explications Explications des +4 événements
1 an plus tard, vous vous voulez voulez changer changer d'outils d'outils d'outils zipkin ne répond plus plus à vos attentes, ou n'est n'est plus mis mis à jour aie aies aie

Solution Solution open tracing façade façade
Principe
Alternative sleuth
Alternative zipkin zippée zipkin
Qui l'utilise
Jaeger
Outils jeunes jeunes, vaut vaut mieux pas pas parier sur sur un outil et trop se se lier à lui






